package zombie.characters;

import zombie.characters.traits.TraitCollection;
import zombie.characters.traits.TraitCollection.TraitSlot;

public class IsoGameCharacter$CharacterTraits extends TraitCollection {
   public final TraitSlot Obese;
   public final TraitSlot Athletic;
   public final TraitSlot Overweight;
   public final TraitSlot Unfit;
   public final TraitSlot Emaciated;
   public final TraitSlot Graceful;
   public final TraitSlot Clumsy;
   public final TraitSlot Strong;
   public final TraitSlot Weak;
   public final TraitSlot VeryUnderweight;
   public final TraitSlot Underweight;
   public final TraitSlot FastHealer;
   public final TraitSlot SlowHealer;
   public final TraitSlot ShortSighted;
   public final TraitSlot EagleEyed;
   public final TraitSlot Agoraphobic;
   public final TraitSlot Claustophobic;
   public final TraitSlot AdrenalineJunkie;
   public final TraitSlot OutOfShape;
   public final TraitSlot HighThirst;
   public final TraitSlot LowThirst;
   public final TraitSlot HeartyAppitite;
   public final TraitSlot LightEater;
   public final TraitSlot Cowardly;
   public final TraitSlot Brave;
   public final TraitSlot Brooding;
   public final TraitSlot Insomniac;
   public final TraitSlot NeedsLessSleep;
   public final TraitSlot NeedsMoreSleep;
   public final TraitSlot Asthmatic;
   public final TraitSlot PlaysFootball;
   public final TraitSlot Jogger;
   public final TraitSlot NightVision;
   public final TraitSlot FastLearner;
   public final TraitSlot SlowLearner;
   public final TraitSlot Pacifist;
   public final TraitSlot Feeble;
   public final TraitSlot Stout;
   public final TraitSlot ShortTemper;
   public final TraitSlot Patient;
   public final TraitSlot Injured;
   public final TraitSlot Inconspicuous;
   public final TraitSlot Conspicuous;
   public final TraitSlot Desensitized;
   public final TraitSlot NightOwl;
   public final TraitSlot Hemophobic;
   public final TraitSlot Burglar;
   public final TraitSlot KeenHearing;
   public final TraitSlot Deaf;
   public final TraitSlot HardOfHearing;
   public final TraitSlot ThinSkinned;
   public final TraitSlot ThickSkinned;
   public final TraitSlot Marksman;
   public final TraitSlot Outdoorsman;
   public final TraitSlot Lucky;
   public final TraitSlot Unlucky;
   public final TraitSlot Nutritionist;
   public final TraitSlot Nutritionist2;
   public final TraitSlot Organized;
   public final TraitSlot Disorganized;
   public final TraitSlot Axeman;
   public final TraitSlot IronGut;
   public final TraitSlot WeakStomach;
   public final TraitSlot HeavyDrinker;
   public final TraitSlot LightDrinker;
   public final TraitSlot Resilient;
   public final TraitSlot ProneToIllness;
   public final TraitSlot SpeedDemon;
   public final TraitSlot SundayDriver;
   public final TraitSlot Smoker;
   public final TraitSlot Hypercondriac;
   public final TraitSlot Illiterate;

   public IsoGameCharacter$CharacterTraits(IsoGameCharacter var1) {
      this.this$0 = var1;
      this.Obese = this.getTraitSlot("Obese");
      this.Athletic = this.getTraitSlot("Athletic");
      this.Overweight = this.getTraitSlot("Overweight");
      this.Unfit = this.getTraitSlot("Unfit");
      this.Emaciated = this.getTraitSlot("Emaciated");
      this.Graceful = this.getTraitSlot("Graceful");
      this.Clumsy = this.getTraitSlot("Clumsy");
      this.Strong = this.getTraitSlot("Strong");
      this.Weak = this.getTraitSlot("Weak");
      this.VeryUnderweight = this.getTraitSlot("Very Underweight");
      this.Underweight = this.getTraitSlot("Underweight");
      this.FastHealer = this.getTraitSlot("FastHealer");
      this.SlowHealer = this.getTraitSlot("SlowHealer");
      this.ShortSighted = this.getTraitSlot("ShortSighted");
      this.EagleEyed = this.getTraitSlot("EagleEyed");
      this.Agoraphobic = this.getTraitSlot("Agoraphobic");
      this.Claustophobic = this.getTraitSlot("Claustophobic");
      this.AdrenalineJunkie = this.getTraitSlot("AdrenalineJunkie");
      this.OutOfShape = this.getTraitSlot("Out of Shape");
      this.HighThirst = this.getTraitSlot("HighThirst");
      this.LowThirst = this.getTraitSlot("LowThirst");
      this.HeartyAppitite = this.getTraitSlot("HeartyAppitite");
      this.LightEater = this.getTraitSlot("LightEater");
      this.Cowardly = this.getTraitSlot("Cowardly");
      this.Brave = this.getTraitSlot("Brave");
      this.Brooding = this.getTraitSlot("Brooding");
      this.Insomniac = this.getTraitSlot("Insomniac");
      this.NeedsLessSleep = this.getTraitSlot("NeedsLessSleep");
      this.NeedsMoreSleep = this.getTraitSlot("NeedsMoreSleep");
      this.Asthmatic = this.getTraitSlot("Asthmatic");
      this.PlaysFootball = this.getTraitSlot("PlaysFootball");
      this.Jogger = this.getTraitSlot("Jogger");
      this.NightVision = this.getTraitSlot("NightVision");
      this.FastLearner = this.getTraitSlot("FastLearner");
      this.SlowLearner = this.getTraitSlot("SlowLearner");
      this.Pacifist = this.getTraitSlot("Pacifist");
      this.Feeble = this.getTraitSlot("Feeble");
      this.Stout = this.getTraitSlot("Stout");
      this.ShortTemper = this.getTraitSlot("ShortTemper");
      this.Patient = this.getTraitSlot("Patient");
      this.Injured = this.getTraitSlot("Injured");
      this.Inconspicuous = this.getTraitSlot("Inconspicuous");
      this.Conspicuous = this.getTraitSlot("Conspicuous");
      this.Desensitized = this.getTraitSlot("Desensitized");
      this.NightOwl = this.getTraitSlot("NightOwl");
      this.Hemophobic = this.getTraitSlot("Hemophobic");
      this.Burglar = this.getTraitSlot("Burglar");
      this.KeenHearing = this.getTraitSlot("KeenHearing");
      this.Deaf = this.getTraitSlot("Deaf");
      this.HardOfHearing = this.getTraitSlot("HardOfHearing");
      this.ThinSkinned = this.getTraitSlot("ThinSkinned");
      this.ThickSkinned = this.getTraitSlot("ThickSkinned");
      this.Marksman = this.getTraitSlot("Marksman");
      this.Outdoorsman = this.getTraitSlot("Outdoorsman");
      this.Lucky = this.getTraitSlot("Lucky");
      this.Unlucky = this.getTraitSlot("Unlucky");
      this.Nutritionist = this.getTraitSlot("Nutritionist");
      this.Nutritionist2 = this.getTraitSlot("Nutritionist2");
      this.Organized = this.getTraitSlot("Organized");
      this.Disorganized = this.getTraitSlot("Disorganized");
      this.Axeman = this.getTraitSlot("Axeman");
      this.IronGut = this.getTraitSlot("IronGut");
      this.WeakStomach = this.getTraitSlot("WeakStomach");
      this.HeavyDrinker = this.getTraitSlot("HeavyDrinker");
      this.LightDrinker = this.getTraitSlot("LightDrinker");
      this.Resilient = this.getTraitSlot("Resilient");
      this.ProneToIllness = this.getTraitSlot("ProneToIllness");
      this.SpeedDemon = this.getTraitSlot("SpeedDemon");
      this.SundayDriver = this.getTraitSlot("SundayDriver");
      this.Smoker = this.getTraitSlot("Smoker");
      this.Hypercondriac = this.getTraitSlot("Hypercondriac");
      this.Illiterate = this.getTraitSlot("Illiterate");
   }

   public boolean isIlliterate() {
      return this.Illiterate.isSet();
   }
}
