#include "fmod/SWIGTYPE_p_FMOD_CREATESOUNDEXINFO.h"

namespace fmod {

protected SWIGTYPE_p_FMOD_CREATESOUNDEXINFO::SWIGTYPE_p_FMOD_CREATESOUNDEXINFO(long long0, bool var3) {
 // TODO: Implement SWIGTYPE_p_FMOD_CREATESOUNDEXINFO
 return nullptr;
}

protected SWIGTYPE_p_FMOD_CREATESOUNDEXINFO::SWIGTYPE_p_FMOD_CREATESOUNDEXINFO() {
 // TODO: Implement SWIGTYPE_p_FMOD_CREATESOUNDEXINFO
 return nullptr;
}

long SWIGTYPE_p_FMOD_CREATESOUNDEXINFO::getCPtr(SWIGTYPE_p_FMOD_CREATESOUNDEXINFO sWIGTYPE_p_FMOD_CREATESOUNDEXINFO) {
 // TODO: Implement getCPtr
 return 0;
}

} // namespace fmod
