#include "fmod/SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK.h"

namespace fmod {

protected SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK::SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK(long long0, bool var3) {
 // TODO: Implement SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK
 return nullptr;
}

protected SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK::SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK() {
 // TODO: Implement SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK
 return nullptr;
}

long SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK::getCPtr(SWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK sWIGTYPE_p_FMOD_FILE_SEEK_CALLBACK) {
 // TODO: Implement getCPtr
 return 0;
}

} // namespace fmod
