#include "fmod/SWIGTYPE_p_FMOD_CODEC_DESCRIPTION.h"

namespace fmod {

protected SWIGTYPE_p_FMOD_CODEC_DESCRIPTION::SWIGTYPE_p_FMOD_CODEC_DESCRIPTION(long long0, bool var3) {
 // TODO: Implement SWIGTYPE_p_FMOD_CODEC_DESCRIPTION
 return nullptr;
}

protected SWIGTYPE_p_FMOD_CODEC_DESCRIPTION::SWIGTYPE_p_FMOD_CODEC_DESCRIPTION() {
 // TODO: Implement SWIGTYPE_p_FMOD_CODEC_DESCRIPTION
 return nullptr;
}

long SWIGTYPE_p_FMOD_CODEC_DESCRIPTION::getCPtr(SWIGTYPE_p_FMOD_CODEC_DESCRIPTION sWIGTYPE_p_FMOD_CODEC_DESCRIPTION) {
 // TODO: Implement getCPtr
 return 0;
}

} // namespace fmod
