#include "fmod/SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR.h"

namespace fmod {

protected
SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR::SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR(
    long long0, bool var3) {
  // TODO: Implement SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR
  return nullptr;
}

protected
SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR::SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR() {
  // TODO: Implement SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR
  return nullptr;
}

long SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR::getCPtr(
    SWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR sWIGTYPE_p_FMOD_SOUNDGROUP_BEHAVIOR) {
  // TODO: Implement getCPtr
  return 0;
}

} // namespace fmod
