#include "fmod/SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK.h"

namespace fmod {

protected SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK::SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK(long var1, bool var3) {
    // TODO: Implement SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK
    return nullptr;
}

protected SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK::SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK() {
    // TODO: Implement SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK
    return nullptr;
}

long SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK::getCPtr(SWIGTYPE_p_FMOD_MEMORY_REALLOC_CALLBACK var0) {
    // TODO: Implement getCPtr
    return 0;
}

} // namespace fmod
