#ifndef ORG_LWJGL_GLFW_GLFWFRAMEBUFFERSIZECALLBACK_H
#define ORG_LWJGL_GLFW_GLFWFRAMEBUFFERSIZECALLBACK_H

namespace org::lwjgl::glfw {
class GLFWFramebufferSizeCallback { };
}

#endif // ORG_LWJGL_GLFW_GLFWFRAMEBUFFERSIZECALLBACK_H
