#ifndef ORG_LWJGL_GLFW_GLFWWINDOWREFRESHCALLBACK_H
#define ORG_LWJGL_GLFW_GLFWWINDOWREFRESHCALLBACK_H

namespace org::lwjgl::glfw {
class GLFWWindowRefreshCallback { };
}

#endif // ORG_LWJGL_GLFW_GLFWWINDOWREFRESHCALLBACK_H
