#ifndef ORG_LWJGL_GLFW_GLFWWINDOWICONIFYCALLBACK_H
#define ORG_LWJGL_GLFW_GLFWWINDOWICONIFYCALLBACK_H

namespace org::lwjgl::glfw {
class GLFWWindowIconifyCallback { };
}

#endif // ORG_LWJGL_GLFW_GLFWWINDOWICONIFYCALLBACK_H
