package zombie.Lua;

import fmod.fmod.EmitterType;
import fmod.fmod.FMODAudio;
import fmod.fmod.FMODSoundBank;
import fmod.fmod.FMODSoundEmitter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Stack;
import java.util.Vector;
import org.joml.Vector2f;
import org.joml.Vector3f;
import org.lwjglx.input.Keyboard;
import se.krka.kahlua.converter.KahluaConverterManager;
import se.krka.kahlua.integration.expose.LuaJavaClassExposer;
import se.krka.kahlua.vm.Coroutine;
import se.krka.kahlua.vm.KahluaTable;
import se.krka.kahlua.vm.KahluaUtil;
import se.krka.kahlua.vm.Platform;
import zombie.AmbientStreamManager;
import zombie.BaseAmbientStreamManager;
import zombie.DummySoundManager;
import zombie.GameSounds;
import zombie.GameTime;
import zombie.GameWindow;
import zombie.MapGroups;
import zombie.SandboxOptions;
import zombie.SoundManager;
import zombie.SystemDisabler;
import zombie.VirtualZombieManager;
import zombie.WorldSoundManager;
import zombie.Lua.LuaManager.GlobalObject;
import zombie.Lua.LuaManager.GlobalObject.LuaFileWriter;
import zombie.SandboxOptions.BooleanSandboxOption;
import zombie.SandboxOptions.DoubleSandboxOption;
import zombie.SandboxOptions.EnumSandboxOption;
import zombie.SandboxOptions.IntegerSandboxOption;
import zombie.SandboxOptions.StringSandboxOption;
import zombie.SoundManager.AmbientSoundEffect;
import zombie.WorldSoundManager.WorldSound;
import zombie.ai.GameCharacterAIBrain;
import zombie.ai.MapKnowledge;
import zombie.ai.sadisticAIDirector.SleepingEvent;
import zombie.ai.states.AttackState;
import zombie.ai.states.BurntToDeath;
import zombie.ai.states.ClimbDownSheetRopeState;
import zombie.ai.states.ClimbOverFenceState;
import zombie.ai.states.ClimbOverWallState;
import zombie.ai.states.ClimbSheetRopeState;
import zombie.ai.states.ClimbThroughWindowState;
import zombie.ai.states.CloseWindowState;
import zombie.ai.states.CrawlingZombieTurnState;
import zombie.ai.states.FakeDeadAttackState;
import zombie.ai.states.FakeDeadZombieState;
import zombie.ai.states.FishingState;
import zombie.ai.states.FitnessState;
import zombie.ai.states.IdleState;
import zombie.ai.states.LungeState;
import zombie.ai.states.OpenWindowState;
import zombie.ai.states.PathFindState;
import zombie.ai.states.PlayerActionsState;
import zombie.ai.states.PlayerAimState;
import zombie.ai.states.PlayerEmoteState;
import zombie.ai.states.PlayerExtState;
import zombie.ai.states.PlayerFallDownState;
import zombie.ai.states.PlayerFallingState;
import zombie.ai.states.PlayerGetUpState;
import zombie.ai.states.PlayerHitReactionPVPState;
import zombie.ai.states.PlayerHitReactionState;
import zombie.ai.states.PlayerKnockedDown;
import zombie.ai.states.PlayerOnGroundState;
import zombie.ai.states.PlayerSitOnGroundState;
import zombie.ai.states.PlayerStrafeState;
import zombie.ai.states.SmashWindowState;
import zombie.ai.states.StaggerBackState;
import zombie.ai.states.SwipeStatePlayer;
import zombie.ai.states.ThumpState;
import zombie.ai.states.WalkTowardState;
import zombie.ai.states.ZombieFallDownState;
import zombie.ai.states.ZombieGetDownState;
import zombie.ai.states.ZombieGetUpState;
import zombie.ai.states.ZombieIdleState;
import zombie.ai.states.ZombieOnGroundState;
import zombie.ai.states.ZombieReanimateState;
import zombie.ai.states.ZombieSittingState;
import zombie.audio.BaseSoundEmitter;
import zombie.audio.DummySoundBank;
import zombie.audio.DummySoundEmitter;
import zombie.audio.GameSound;
import zombie.audio.GameSoundClip;
import zombie.characterTextures.BloodBodyPartType;
import zombie.characterTextures.BloodClothingType;
import zombie.characters.CharacterActionAnims;
import zombie.characters.CharacterSoundEmitter;
import zombie.characters.DummyCharacterSoundEmitter;
import zombie.characters.Faction;
import zombie.characters.HaloTextHelper;
import zombie.characters.IsoDummyCameraCharacter;
import zombie.characters.IsoGameCharacter;
import zombie.characters.IsoPlayer;
import zombie.characters.IsoSurvivor;
import zombie.characters.IsoZombie;
import zombie.characters.Safety;
import zombie.characters.Stats;
import zombie.characters.SurvivorDesc;
import zombie.characters.SurvivorFactory;
import zombie.characters.AttachedItems.AttachedItem;
import zombie.characters.AttachedItems.AttachedItems;
import zombie.characters.AttachedItems.AttachedLocation;
import zombie.characters.AttachedItems.AttachedLocationGroup;
import zombie.characters.AttachedItems.AttachedLocations;
import zombie.characters.BodyDamage.BodyDamage;
import zombie.characters.BodyDamage.BodyPart;
import zombie.characters.BodyDamage.BodyPartType;
import zombie.characters.BodyDamage.Fitness;
import zombie.characters.BodyDamage.Metabolics;
import zombie.characters.BodyDamage.Nutrition;
import zombie.characters.BodyDamage.Thermoregulator;
import zombie.characters.BodyDamage.Thermoregulator.ThermalNode;
import zombie.characters.CharacterTimedActions.LuaTimedAction;
import zombie.characters.CharacterTimedActions.LuaTimedActionNew;
import zombie.characters.HaloTextHelper.ColorRGB;
import zombie.characters.IsoGameCharacter.CharacterTraits;
import zombie.characters.IsoGameCharacter.Location;
import zombie.characters.IsoGameCharacter.PerkInfo;
import zombie.characters.IsoGameCharacter.XP;
import zombie.characters.Moodles.Moodle;
import zombie.characters.Moodles.MoodleType;
import zombie.characters.Moodles.Moodles;
import zombie.characters.SurvivorFactory.SurvivorType;
import zombie.characters.WornItems.BodyLocation;
import zombie.characters.WornItems.BodyLocationGroup;
import zombie.characters.WornItems.BodyLocations;
import zombie.characters.WornItems.WornItem;
import zombie.characters.WornItems.WornItems;
import zombie.characters.professions.ProfessionFactory;
import zombie.characters.professions.ProfessionFactory.Profession;
import zombie.characters.skills.PerkFactory;
import zombie.characters.skills.PerkFactory.Perk;
import zombie.characters.skills.PerkFactory.Perks;
import zombie.characters.traits.ObservationFactory;
import zombie.characters.traits.TraitCollection;
import zombie.characters.traits.TraitFactory;
import zombie.characters.traits.ObservationFactory.Observation;
import zombie.characters.traits.TraitCollection.TraitSlot;
import zombie.characters.traits.TraitFactory.Trait;
import zombie.chat.ChatBase;
import zombie.chat.ChatMessage;
import zombie.chat.ServerChatMessage;
import zombie.config.BooleanConfigOption;
import zombie.config.ConfigOption;
import zombie.config.DoubleConfigOption;
import zombie.config.EnumConfigOption;
import zombie.config.IntegerConfigOption;
import zombie.config.StringConfigOption;
import zombie.core.Clipboard;
import zombie.core.Color;
import zombie.core.Colors;
import zombie.core.Core;
import zombie.core.GameVersion;
import zombie.core.ImmutableColor;
import zombie.core.Language;
import zombie.core.PerformanceSettings;
import zombie.core.SpriteRenderer;
import zombie.core.Translator;
import zombie.core.fonts.AngelCodeFont;
import zombie.core.logger.ZLogger;
import zombie.core.math.PZMath;
import zombie.core.properties.PropertyContainer;
import zombie.core.skinnedmodel.advancedanimation.debug.AnimatorDebugMonitor;
import zombie.core.skinnedmodel.population.BeardStyle;
import zombie.core.skinnedmodel.population.BeardStyles;
import zombie.core.skinnedmodel.population.ClothingItem;
import zombie.core.skinnedmodel.population.HairStyle;
import zombie.core.skinnedmodel.population.HairStyles;
import zombie.core.skinnedmodel.visual.HumanVisual;
import zombie.core.skinnedmodel.visual.ItemVisual;
import zombie.core.skinnedmodel.visual.ItemVisuals;
import zombie.core.stash.Stash;
import zombie.core.stash.StashBuilding;
import zombie.core.stash.StashSystem;
import zombie.core.textures.ColorInfo;
import zombie.core.textures.Texture;
import zombie.core.znet.SteamFriend;
import zombie.core.znet.SteamUGCDetails;
import zombie.core.znet.SteamWorkshopItem;
import zombie.debug.BooleanDebugOption;
import zombie.debug.DebugLog;
import zombie.debug.DebugOptions;
import zombie.debug.DebugType;
import zombie.erosion.ErosionConfig;
import zombie.erosion.ErosionMain;
import zombie.erosion.ErosionConfig.Debug;
import zombie.erosion.ErosionConfig.Season;
import zombie.erosion.ErosionConfig.Seeds;
import zombie.erosion.ErosionConfig.Time;
import zombie.erosion.season.ErosionSeason;
import zombie.gameStates.AnimationViewerState;
import zombie.gameStates.AttachmentEditorState;
import zombie.gameStates.DebugChunkState;
import zombie.gameStates.DebugGlobalObjectState;
import zombie.gameStates.GameLoadingState;
import zombie.gameStates.LoadingQueueState;
import zombie.gameStates.MainScreenState;
import zombie.gameStates.TermsOfServiceState;
import zombie.gameStates.ChooseGameInfo.Mod;
import zombie.globalObjects.CGlobalObject;
import zombie.globalObjects.CGlobalObjectSystem;
import zombie.globalObjects.CGlobalObjects;
import zombie.globalObjects.SGlobalObject;
import zombie.globalObjects.SGlobalObjectSystem;
import zombie.globalObjects.SGlobalObjects;
import zombie.input.GameKeyboard;
import zombie.input.Mouse;
import zombie.inventory.FixingManager;
import zombie.inventory.InventoryItem;
import zombie.inventory.InventoryItemFactory;
import zombie.inventory.ItemContainer;
import zombie.inventory.ItemPickerJava;
import zombie.inventory.ItemType;
import zombie.inventory.RecipeManager;
import zombie.inventory.types.AlarmClock;
import zombie.inventory.types.AlarmClockClothing;
import zombie.inventory.types.Clothing;
import zombie.inventory.types.ComboItem;
import zombie.inventory.types.Drainable;
import zombie.inventory.types.DrainableComboItem;
import zombie.inventory.types.Food;
import zombie.inventory.types.HandWeapon;
import zombie.inventory.types.InventoryContainer;
import zombie.inventory.types.Key;
import zombie.inventory.types.KeyRing;
import zombie.inventory.types.Literature;
import zombie.inventory.types.MapItem;
import zombie.inventory.types.Moveable;
import zombie.inventory.types.Radio;
import zombie.inventory.types.WeaponPart;
import zombie.inventory.types.WeaponType;
import zombie.inventory.types.Clothing.ClothingPatch;
import zombie.inventory.types.Clothing.ClothingPatchFabricType;
import zombie.iso.BentFences;
import zombie.iso.BrokenFences;
import zombie.iso.BuildingDef;
import zombie.iso.ContainerOverlays;
import zombie.iso.IsoCamera;
import zombie.iso.IsoCell;
import zombie.iso.IsoChunk;
import zombie.iso.IsoChunkMap;
import zombie.iso.IsoDirectionSet;
import zombie.iso.IsoDirections;
import zombie.iso.IsoGridSquare;
import zombie.iso.IsoHeatSource;
import zombie.iso.IsoLightSource;
import zombie.iso.IsoLot;
import zombie.iso.IsoLuaMover;
import zombie.iso.IsoMarkers;
import zombie.iso.IsoMetaCell;
import zombie.iso.IsoMetaChunk;
import zombie.iso.IsoMetaGrid;
import zombie.iso.IsoMovingObject;
import zombie.iso.IsoObject;
import zombie.iso.IsoObjectPicker;
import zombie.iso.IsoPuddles;
import zombie.iso.IsoPushableObject;
import zombie.iso.IsoUtils;
import zombie.iso.IsoWaterGeometry;
import zombie.iso.IsoWorld;
import zombie.iso.LosUtil;
import zombie.iso.MetaObject;
import zombie.iso.MultiStageBuilding;
import zombie.iso.RoomDef;
import zombie.iso.SearchMode;
import zombie.iso.SliceY;
import zombie.iso.TileOverlays;
import zombie.iso.Vector2;
import zombie.iso.Vector3;
import zombie.iso.WorldMarkers;
import zombie.iso.IsoMarkers.CircleIsoMarker;
import zombie.iso.IsoMarkers.IsoMarker;
import zombie.iso.IsoMetaGrid.Trigger;
import zombie.iso.IsoMetaGrid.VehicleZone;
import zombie.iso.IsoMetaGrid.Zone;
import zombie.iso.IsoPuddles.PuddlesFloat;
import zombie.iso.MultiStageBuilding.Stage;
import zombie.iso.SearchMode.PlayerSearchMode;
import zombie.iso.SearchMode.SearchModeFloat;
import zombie.iso.SpriteDetails.IsoFlagType;
import zombie.iso.SpriteDetails.IsoObjectType;
import zombie.iso.WorldMarkers.DirectionArrow;
import zombie.iso.WorldMarkers.GridSquareMarker;
import zombie.iso.WorldMarkers.PlayerHomingPoint;
import zombie.iso.areas.IsoBuilding;
import zombie.iso.areas.IsoRoom;
import zombie.iso.areas.NonPvpZone;
import zombie.iso.areas.SafeHouse;
import zombie.iso.areas.isoregion.IsoRegionLogType;
import zombie.iso.areas.isoregion.IsoRegions;
import zombie.iso.areas.isoregion.IsoRegionsLogger;
import zombie.iso.areas.isoregion.IsoRegionsRenderer;
import zombie.iso.areas.isoregion.IsoRegionsLogger.IsoRegionLog;
import zombie.iso.areas.isoregion.data.DataCell;
import zombie.iso.areas.isoregion.data.DataChunk;
import zombie.iso.areas.isoregion.regions.IsoChunkRegion;
import zombie.iso.areas.isoregion.regions.IsoWorldRegion;
import zombie.iso.objects.BSFurnace;
import zombie.iso.objects.IsoBarbecue;
import zombie.iso.objects.IsoBarricade;
import zombie.iso.objects.IsoBrokenGlass;
import zombie.iso.objects.IsoCarBatteryCharger;
import zombie.iso.objects.IsoClothingDryer;
import zombie.iso.objects.IsoClothingWasher;
import zombie.iso.objects.IsoCombinationWasherDryer;
import zombie.iso.objects.IsoCompost;
import zombie.iso.objects.IsoCurtain;
import zombie.iso.objects.IsoDeadBody;
import zombie.iso.objects.IsoDoor;
import zombie.iso.objects.IsoFire;
import zombie.iso.objects.IsoFireManager;
import zombie.iso.objects.IsoFireplace;
import zombie.iso.objects.IsoGenerator;
import zombie.iso.objects.IsoJukebox;
import zombie.iso.objects.IsoLightSwitch;
import zombie.iso.objects.IsoMannequin;
import zombie.iso.objects.IsoMolotovCocktail;
import zombie.iso.objects.IsoRadio;
import zombie.iso.objects.IsoStackedWasherDryer;
import zombie.iso.objects.IsoStove;
import zombie.iso.objects.IsoTelevision;
import zombie.iso.objects.IsoThumpable;
import zombie.iso.objects.IsoTrap;
import zombie.iso.objects.IsoTree;
import zombie.iso.objects.IsoWaveSignal;
import zombie.iso.objects.IsoWheelieBin;
import zombie.iso.objects.IsoWindow;
import zombie.iso.objects.IsoWindowFrame;
import zombie.iso.objects.IsoWorldInventoryObject;
import zombie.iso.objects.IsoZombieGiblets;
import zombie.iso.objects.ObjectRenderEffects;
import zombie.iso.objects.RainManager;
import zombie.iso.objects.interfaces.BarricadeAble;
import zombie.iso.sprite.IsoSprite;
import zombie.iso.sprite.IsoSpriteGrid;
import zombie.iso.sprite.IsoSpriteInstance;
import zombie.iso.sprite.IsoSpriteManager;
import zombie.iso.weather.ClimateColorInfo;
import zombie.iso.weather.ClimateForecaster;
import zombie.iso.weather.ClimateHistory;
import zombie.iso.weather.ClimateManager;
import zombie.iso.weather.ClimateMoon;
import zombie.iso.weather.ClimateValues;
import zombie.iso.weather.Temperature;
import zombie.iso.weather.ThunderStorm;
import zombie.iso.weather.WeatherPeriod;
import zombie.iso.weather.WorldFlares;
import zombie.iso.weather.ClimateForecaster.DayForecast;
import zombie.iso.weather.ClimateForecaster.ForecastValue;
import zombie.iso.weather.ClimateManager.AirFront;
import zombie.iso.weather.ClimateManager.ClimateBool;
import zombie.iso.weather.ClimateManager.ClimateColor;
import zombie.iso.weather.ClimateManager.ClimateFloat;
import zombie.iso.weather.ClimateManager.DayInfo;
import zombie.iso.weather.ThunderStorm.ThunderCloud;
import zombie.iso.weather.WeatherPeriod.StrLerpVal;
import zombie.iso.weather.WeatherPeriod.WeatherStage;
import zombie.iso.weather.WorldFlares.Flare;
import zombie.iso.weather.fog.ImprovedFog;
import zombie.iso.weather.fx.IsoWeatherFX;
import zombie.modding.ActiveMods;
import zombie.network.DBResult;
import zombie.network.DBTicket;
import zombie.network.NetworkAIParams;
import zombie.network.Server;
import zombie.network.ServerOptions;
import zombie.network.ServerSettings;
import zombie.network.ServerSettingsManager;
import zombie.network.Userlog;
import zombie.network.ServerOptions.BooleanServerOption;
import zombie.network.ServerOptions.DoubleServerOption;
import zombie.network.ServerOptions.IntegerServerOption;
import zombie.network.ServerOptions.StringServerOption;
import zombie.network.ServerOptions.TextServerOption;
import zombie.network.Userlog.UserlogType;
import zombie.popman.ZombiePopulationRenderer;
import zombie.radio.ChannelCategory;
import zombie.radio.RadioAPI;
import zombie.radio.RadioData;
import zombie.radio.ZomboidRadio;
import zombie.radio.StorySounds.DataPoint;
import zombie.radio.StorySounds.EventSound;
import zombie.radio.StorySounds.SLSoundManager;
import zombie.radio.StorySounds.StorySound;
import zombie.radio.StorySounds.StorySoundEvent;
import zombie.radio.devices.DeviceData;
import zombie.radio.devices.DevicePresets;
import zombie.radio.devices.PresetEntry;
import zombie.radio.media.MediaData;
import zombie.radio.media.RecordedMedia;
import zombie.radio.media.MediaData.MediaLineData;
import zombie.radio.scripting.DynamicRadioChannel;
import zombie.radio.scripting.RadioBroadCast;
import zombie.radio.scripting.RadioChannel;
import zombie.radio.scripting.RadioLine;
import zombie.radio.scripting.RadioScript;
import zombie.radio.scripting.RadioScriptManager;
import zombie.radio.scripting.RadioScript.ExitOption;
import zombie.randomizedWorld.RandomizedWorldBase;
import zombie.randomizedWorld.randomizedBuilding.RBBar;
import zombie.randomizedWorld.randomizedBuilding.RBBasic;
import zombie.randomizedWorld.randomizedBuilding.RBBurnt;
import zombie.randomizedWorld.randomizedBuilding.RBBurntCorpse;
import zombie.randomizedWorld.randomizedBuilding.RBBurntFireman;
import zombie.randomizedWorld.randomizedBuilding.RBCafe;
import zombie.randomizedWorld.randomizedBuilding.RBClinic;
import zombie.randomizedWorld.randomizedBuilding.RBHairSalon;
import zombie.randomizedWorld.randomizedBuilding.RBKateAndBaldspot;
import zombie.randomizedWorld.randomizedBuilding.RBLooted;
import zombie.randomizedWorld.randomizedBuilding.RBOffice;
import zombie.randomizedWorld.randomizedBuilding.RBOther;
import zombie.randomizedWorld.randomizedBuilding.RBPileOCrepe;
import zombie.randomizedWorld.randomizedBuilding.RBPizzaWhirled;
import zombie.randomizedWorld.randomizedBuilding.RBSafehouse;
import zombie.randomizedWorld.randomizedBuilding.RBSchool;
import zombie.randomizedWorld.randomizedBuilding.RBShopLooted;
import zombie.randomizedWorld.randomizedBuilding.RBSpiffo;
import zombie.randomizedWorld.randomizedBuilding.RBStripclub;
import zombie.randomizedWorld.randomizedBuilding.RandomizedBuildingBase;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSBandPractice;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSBathroomZed;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSBedroomZed;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSBleach;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSCorpsePsycho;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSDeadDrunk;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSFootballNight;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSGunmanInBathroom;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSGunslinger;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSHenDo;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSHockeyPsycho;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSHouseParty;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSPokerNight;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSPoliceAtHouse;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSPrisonEscape;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSPrisonEscapeWithPolice;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSSkeletonPsycho;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSSpecificProfession;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSStagDo;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSStudentNight;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSSuicidePact;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSTinFoilHat;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSZombieLockedBathroom;
import zombie.randomizedWorld.randomizedDeadSurvivor.RDSZombiesEating;
import zombie.randomizedWorld.randomizedDeadSurvivor.RandomizedDeadSurvivorBase;
import zombie.randomizedWorld.randomizedVehicleStory.RVSAmbulanceCrash;
import zombie.randomizedWorld.randomizedVehicleStory.RVSBanditRoad;
import zombie.randomizedWorld.randomizedVehicleStory.RVSBurntCar;
import zombie.randomizedWorld.randomizedVehicleStory.RVSCarCrash;
import zombie.randomizedWorld.randomizedVehicleStory.RVSCarCrashCorpse;
import zombie.randomizedWorld.randomizedVehicleStory.RVSChangingTire;
import zombie.randomizedWorld.randomizedVehicleStory.RVSConstructionSite;
import zombie.randomizedWorld.randomizedVehicleStory.RVSCrashHorde;
import zombie.randomizedWorld.randomizedVehicleStory.RVSFlippedCrash;
import zombie.randomizedWorld.randomizedVehicleStory.RVSPoliceBlockade;
import zombie.randomizedWorld.randomizedVehicleStory.RVSPoliceBlockadeShooting;
import zombie.randomizedWorld.randomizedVehicleStory.RVSTrailerCrash;
import zombie.randomizedWorld.randomizedVehicleStory.RVSUtilityVehicle;
import zombie.randomizedWorld.randomizedVehicleStory.RandomizedVehicleStoryBase;
import zombie.randomizedWorld.randomizedZoneStory.RZSBBQParty;
import zombie.randomizedWorld.randomizedZoneStory.RZSBaseball;
import zombie.randomizedWorld.randomizedZoneStory.RZSBeachParty;
import zombie.randomizedWorld.randomizedZoneStory.RZSBuryingCamp;
import zombie.randomizedWorld.randomizedZoneStory.RZSFishingTrip;
import zombie.randomizedWorld.randomizedZoneStory.RZSForestCamp;
import zombie.randomizedWorld.randomizedZoneStory.RZSForestCampEaten;
import zombie.randomizedWorld.randomizedZoneStory.RZSHunterCamp;
import zombie.randomizedWorld.randomizedZoneStory.RZSMusicFest;
import zombie.randomizedWorld.randomizedZoneStory.RZSMusicFestStage;
import zombie.randomizedWorld.randomizedZoneStory.RZSSexyTime;
import zombie.randomizedWorld.randomizedZoneStory.RZSTrapperCamp;
import zombie.randomizedWorld.randomizedZoneStory.RandomizedZoneStoryBase;
import zombie.scripting.ScriptManager;
import zombie.scripting.objects.EvolvedRecipe;
import zombie.scripting.objects.Fixing;
import zombie.scripting.objects.GameSoundScript;
import zombie.scripting.objects.Item;
import zombie.scripting.objects.ItemRecipe;
import zombie.scripting.objects.MannequinScript;
import zombie.scripting.objects.ModelAttachment;
import zombie.scripting.objects.ModelScript;
import zombie.scripting.objects.MovableRecipe;
import zombie.scripting.objects.Recipe;
import zombie.scripting.objects.ScriptModule;
import zombie.scripting.objects.VehicleScript;
import zombie.scripting.objects.Fixing.Fixer;
import zombie.scripting.objects.Fixing.FixerSkill;
import zombie.scripting.objects.Item.Type;
import zombie.scripting.objects.Recipe.RequiredSkill;
import zombie.scripting.objects.Recipe.Result;
import zombie.scripting.objects.Recipe.Source;
import zombie.scripting.objects.VehicleScript.Area;
import zombie.scripting.objects.VehicleScript.Model;
import zombie.scripting.objects.VehicleScript.Part;
import zombie.scripting.objects.VehicleScript.Passenger;
import zombie.scripting.objects.VehicleScript.PhysicsShape;
import zombie.scripting.objects.VehicleScript.Position;
import zombie.scripting.objects.VehicleScript.Wheel;
import zombie.text.templating.ReplaceProviderCharacter;
import zombie.text.templating.TemplateText;
import zombie.ui.ActionProgressBar;
import zombie.ui.Clock;
import zombie.ui.ModalDialog;
import zombie.ui.MoodlesUI;
import zombie.ui.NewHealthPanel;
import zombie.ui.ObjectTooltip;
import zombie.ui.RadarPanel;
import zombie.ui.RadialMenu;
import zombie.ui.RadialProgressBar;
import zombie.ui.SpeedControls;
import zombie.ui.TextDrawObject;
import zombie.ui.TextManager;
import zombie.ui.UI3DModel;
import zombie.ui.UIDebugConsole;
import zombie.ui.UIElement;
import zombie.ui.UIFont;
import zombie.ui.UIManager;
import zombie.ui.UIServerToolbox;
import zombie.ui.UITextBox2;
import zombie.ui.UITransition;
import zombie.ui.VehicleGauge;
import zombie.ui.ObjectTooltip.Layout;
import zombie.ui.ObjectTooltip.LayoutItem;
import zombie.util.PZCalendar;
import zombie.util.list.PZArrayList;
import zombie.vehicles.BaseVehicle;
import zombie.vehicles.EditVehicleState;
import zombie.vehicles.PathFindBehavior2;
import zombie.vehicles.PathFindState2;
import zombie.vehicles.UI3DScene;
import zombie.vehicles.VehicleDoor;
import zombie.vehicles.VehicleLight;
import zombie.vehicles.VehiclePart;
import zombie.vehicles.VehicleType;
import zombie.vehicles.VehicleWindow;
import zombie.vehicles.PathFindBehavior2.BehaviorResult;
import zombie.world.moddata.ModData;
import zombie.worldMap.UIWorldMap;

public final class LuaManager$Exposer extends LuaJavaClassExposer {
   private final HashSet<Class<?>> exposed = new HashSet<>();

   public LuaManager$Exposer(KahluaConverterManager var1, Platform var2, KahluaTable var3) {
      super(var1, var2, var3);
   }

   public void exposeAll() {
      this.setExposed(BufferedReader.class);
      this.setExposed(BufferedWriter.class);
      this.setExposed(DataInputStream.class);
      this.setExposed(DataOutputStream.class);
      this.setExposed(Double.class);
      this.setExposed(Long.class);
      this.setExposed(Float.class);
      this.setExposed(Integer.class);
      this.setExposed(Math.class);
      this.setExposed(Void.class);
      this.setExposed(SimpleDateFormat.class);
      this.setExposed(ArrayList.class);
      this.setExposed(EnumMap.class);
      this.setExposed(HashMap.class);
      this.setExposed(LinkedList.class);
      this.setExposed(Stack.class);
      this.setExposed(Vector.class);
      this.setExposed(Iterator.class);
      this.setExposed(EmitterType.class);
      this.setExposed(FMODAudio.class);
      this.setExposed(FMODSoundBank.class);
      this.setExposed(FMODSoundEmitter.class);
      this.setExposed(Vector2f.class);
      this.setExposed(Vector3f.class);
      this.setExposed(KahluaUtil.class);
      this.setExposed(DummySoundBank.class);
      this.setExposed(DummySoundEmitter.class);
      this.setExposed(BaseSoundEmitter.class);
      this.setExposed(GameSound.class);
      this.setExposed(GameSoundClip.class);
      this.setExposed(AttackState.class);
      this.setExposed(BurntToDeath.class);
      this.setExposed(ClimbDownSheetRopeState.class);
      this.setExposed(ClimbOverFenceState.class);
      this.setExposed(ClimbOverWallState.class);
      this.setExposed(ClimbSheetRopeState.class);
      this.setExposed(ClimbThroughWindowState.class);
      this.setExposed(CloseWindowState.class);
      this.setExposed(CrawlingZombieTurnState.class);
      this.setExposed(FakeDeadAttackState.class);
      this.setExposed(FakeDeadZombieState.class);
      this.setExposed(FishingState.class);
      this.setExposed(FitnessState.class);
      this.setExposed(IdleState.class);
      this.setExposed(LungeState.class);
      this.setExposed(OpenWindowState.class);
      this.setExposed(PathFindState.class);
      this.setExposed(PlayerActionsState.class);
      this.setExposed(PlayerAimState.class);
      this.setExposed(PlayerEmoteState.class);
      this.setExposed(PlayerExtState.class);
      this.setExposed(PlayerFallDownState.class);
      this.setExposed(PlayerFallingState.class);
      this.setExposed(PlayerGetUpState.class);
      this.setExposed(PlayerHitReactionPVPState.class);
      this.setExposed(PlayerHitReactionState.class);
      this.setExposed(PlayerKnockedDown.class);
      this.setExposed(PlayerOnGroundState.class);
      this.setExposed(PlayerSitOnGroundState.class);
      this.setExposed(PlayerStrafeState.class);
      this.setExposed(SmashWindowState.class);
      this.setExposed(StaggerBackState.class);
      this.setExposed(SwipeStatePlayer.class);
      this.setExposed(ThumpState.class);
      this.setExposed(WalkTowardState.class);
      this.setExposed(ZombieFallDownState.class);
      this.setExposed(ZombieGetDownState.class);
      this.setExposed(ZombieGetUpState.class);
      this.setExposed(ZombieIdleState.class);
      this.setExposed(ZombieOnGroundState.class);
      this.setExposed(ZombieReanimateState.class);
      this.setExposed(ZombieSittingState.class);
      this.setExposed(GameCharacterAIBrain.class);
      this.setExposed(MapKnowledge.class);
      this.setExposed(BodyPartType.class);
      this.setExposed(BodyPart.class);
      this.setExposed(BodyDamage.class);
      this.setExposed(Thermoregulator.class);
      this.setExposed(ThermalNode.class);
      this.setExposed(Metabolics.class);
      this.setExposed(Fitness.class);
      this.setExposed(GameKeyboard.class);
      this.setExposed(LuaTimedAction.class);
      this.setExposed(LuaTimedActionNew.class);
      this.setExposed(Moodle.class);
      this.setExposed(Moodles.class);
      this.setExposed(MoodleType.class);
      this.setExposed(ProfessionFactory.class);
      this.setExposed(Profession.class);
      this.setExposed(PerkFactory.class);
      this.setExposed(Perk.class);
      this.setExposed(Perks.class);
      this.setExposed(ObservationFactory.class);
      this.setExposed(Observation.class);
      this.setExposed(TraitFactory.class);
      this.setExposed(Trait.class);
      this.setExposed(IsoDummyCameraCharacter.class);
      this.setExposed(Stats.class);
      this.setExposed(SurvivorDesc.class);
      this.setExposed(SurvivorFactory.class);
      this.setExposed(SurvivorType.class);
      this.setExposed(IsoGameCharacter.class);
      this.setExposed(Location.class);
      this.setExposed(PerkInfo.class);
      this.setExposed(XP.class);
      this.setExposed(CharacterTraits.class);
      this.setExposed(TraitSlot.class);
      this.setExposed(TraitCollection.class);
      this.setExposed(IsoPlayer.class);
      this.setExposed(IsoSurvivor.class);
      this.setExposed(IsoZombie.class);
      this.setExposed(CharacterActionAnims.class);
      this.setExposed(HaloTextHelper.class);
      this.setExposed(ColorRGB.class);
      this.setExposed(NetworkAIParams.class);
      this.setExposed(BloodBodyPartType.class);
      this.setExposed(Clipboard.class);
      this.setExposed(AngelCodeFont.class);
      this.setExposed(ZLogger.class);
      this.setExposed(PropertyContainer.class);
      this.setExposed(ClothingItem.class);
      this.setExposed(AnimatorDebugMonitor.class);
      this.setExposed(ColorInfo.class);
      this.setExposed(Texture.class);
      this.setExposed(SteamFriend.class);
      this.setExposed(SteamUGCDetails.class);
      this.setExposed(SteamWorkshopItem.class);
      this.setExposed(Color.class);
      this.setExposed(Colors.class);
      this.setExposed(Core.class);
      this.setExposed(GameVersion.class);
      this.setExposed(ImmutableColor.class);
      this.setExposed(Language.class);
      this.setExposed(PerformanceSettings.class);
      this.setExposed(SpriteRenderer.class);
      this.setExposed(Translator.class);
      this.setExposed(PZMath.class);
      this.setExposed(DebugLog.class);
      this.setExposed(DebugOptions.class);
      this.setExposed(BooleanDebugOption.class);
      this.setExposed(DebugType.class);
      this.setExposed(ErosionConfig.class);
      this.setExposed(Debug.class);
      this.setExposed(Season.class);
      this.setExposed(Seeds.class);
      this.setExposed(Time.class);
      this.setExposed(ErosionMain.class);
      this.setExposed(ErosionSeason.class);
      this.setExposed(AnimationViewerState.class);
      this.setExposed(zombie.gameStates.AnimationViewerState.BooleanDebugOption.class);
      this.setExposed(AttachmentEditorState.class);
      this.setExposed(Mod.class);
      this.setExposed(DebugChunkState.class);
      this.setExposed(zombie.gameStates.DebugChunkState.BooleanDebugOption.class);
      this.setExposed(DebugGlobalObjectState.class);
      this.setExposed(GameLoadingState.class);
      this.setExposed(LoadingQueueState.class);
      this.setExposed(MainScreenState.class);
      this.setExposed(TermsOfServiceState.class);
      this.setExposed(CGlobalObject.class);
      this.setExposed(CGlobalObjects.class);
      this.setExposed(CGlobalObjectSystem.class);
      this.setExposed(SGlobalObject.class);
      this.setExposed(SGlobalObjects.class);
      this.setExposed(SGlobalObjectSystem.class);
      this.setExposed(Mouse.class);
      this.setExposed(AlarmClock.class);
      this.setExposed(AlarmClockClothing.class);
      this.setExposed(Clothing.class);
      this.setExposed(ClothingPatch.class);
      this.setExposed(ClothingPatchFabricType.class);
      this.setExposed(ComboItem.class);
      this.setExposed(Drainable.class);
      this.setExposed(DrainableComboItem.class);
      this.setExposed(Food.class);
      this.setExposed(HandWeapon.class);
      this.setExposed(InventoryContainer.class);
      this.setExposed(Key.class);
      this.setExposed(KeyRing.class);
      this.setExposed(Literature.class);
      this.setExposed(MapItem.class);
      this.setExposed(Moveable.class);
      this.setExposed(Radio.class);
      this.setExposed(WeaponPart.class);
      this.setExposed(ItemContainer.class);
      this.setExposed(ItemPickerJava.class);
      this.setExposed(InventoryItem.class);
      this.setExposed(InventoryItemFactory.class);
      this.setExposed(FixingManager.class);
      this.setExposed(RecipeManager.class);
      this.setExposed(IsoRegions.class);
      this.setExposed(IsoRegionsLogger.class);
      this.setExposed(IsoRegionLog.class);
      this.setExposed(IsoRegionLogType.class);
      this.setExposed(DataCell.class);
      this.setExposed(DataChunk.class);
      this.setExposed(IsoChunkRegion.class);
      this.setExposed(IsoWorldRegion.class);
      this.setExposed(IsoRegionsRenderer.class);
      this.setExposed(zombie.iso.areas.isoregion.IsoRegionsRenderer.BooleanDebugOption.class);
      this.setExposed(IsoBuilding.class);
      this.setExposed(IsoRoom.class);
      this.setExposed(SafeHouse.class);
      this.setExposed(BarricadeAble.class);
      this.setExposed(IsoBarbecue.class);
      this.setExposed(IsoBarricade.class);
      this.setExposed(IsoBrokenGlass.class);
      this.setExposed(IsoClothingDryer.class);
      this.setExposed(IsoClothingWasher.class);
      this.setExposed(IsoCombinationWasherDryer.class);
      this.setExposed(IsoStackedWasherDryer.class);
      this.setExposed(IsoCurtain.class);
      this.setExposed(IsoCarBatteryCharger.class);
      this.setExposed(IsoDeadBody.class);
      this.setExposed(IsoDoor.class);
      this.setExposed(IsoFire.class);
      this.setExposed(IsoFireManager.class);
      this.setExposed(IsoFireplace.class);
      this.setExposed(IsoGenerator.class);
      this.setExposed(IsoJukebox.class);
      this.setExposed(IsoLightSwitch.class);
      this.setExposed(IsoMannequin.class);
      this.setExposed(IsoMolotovCocktail.class);
      this.setExposed(IsoWaveSignal.class);
      this.setExposed(IsoRadio.class);
      this.setExposed(IsoTelevision.class);
      this.setExposed(IsoStackedWasherDryer.class);
      this.setExposed(IsoStove.class);
      this.setExposed(IsoThumpable.class);
      this.setExposed(IsoTrap.class);
      this.setExposed(IsoTree.class);
      this.setExposed(IsoWheelieBin.class);
      this.setExposed(IsoWindow.class);
      this.setExposed(IsoWindowFrame.class);
      this.setExposed(IsoWorldInventoryObject.class);
      this.setExposed(IsoZombieGiblets.class);
      this.setExposed(RainManager.class);
      this.setExposed(ObjectRenderEffects.class);
      this.setExposed(HumanVisual.class);
      this.setExposed(ItemVisual.class);
      this.setExposed(ItemVisuals.class);
      this.setExposed(IsoSprite.class);
      this.setExposed(IsoSpriteInstance.class);
      this.setExposed(IsoSpriteManager.class);
      this.setExposed(IsoSpriteGrid.class);
      this.setExposed(IsoFlagType.class);
      this.setExposed(IsoObjectType.class);
      this.setExposed(ClimateManager.class);
      this.setExposed(DayInfo.class);
      this.setExposed(ClimateFloat.class);
      this.setExposed(ClimateColor.class);
      this.setExposed(ClimateBool.class);
      this.setExposed(WeatherPeriod.class);
      this.setExposed(WeatherStage.class);
      this.setExposed(StrLerpVal.class);
      this.setExposed(AirFront.class);
      this.setExposed(ThunderStorm.class);
      this.setExposed(ThunderCloud.class);
      this.setExposed(IsoWeatherFX.class);
      this.setExposed(Temperature.class);
      this.setExposed(ClimateColorInfo.class);
      this.setExposed(ClimateValues.class);
      this.setExposed(ClimateForecaster.class);
      this.setExposed(DayForecast.class);
      this.setExposed(ForecastValue.class);
      this.setExposed(ClimateHistory.class);
      this.setExposed(WorldFlares.class);
      this.setExposed(Flare.class);
      this.setExposed(ImprovedFog.class);
      this.setExposed(ClimateMoon.class);
      this.setExposed(IsoPuddles.class);
      this.setExposed(PuddlesFloat.class);
      this.setExposed(BentFences.class);
      this.setExposed(BrokenFences.class);
      this.setExposed(ContainerOverlays.class);
      this.setExposed(IsoChunk.class);
      this.setExposed(BuildingDef.class);
      this.setExposed(IsoCamera.class);
      this.setExposed(IsoCell.class);
      this.setExposed(IsoChunkMap.class);
      this.setExposed(IsoDirections.class);
      this.setExposed(IsoDirectionSet.class);
      this.setExposed(IsoGridSquare.class);
      this.setExposed(IsoHeatSource.class);
      this.setExposed(IsoLightSource.class);
      this.setExposed(IsoLot.class);
      this.setExposed(IsoLuaMover.class);
      this.setExposed(IsoMetaChunk.class);
      this.setExposed(IsoMetaCell.class);
      this.setExposed(IsoMetaGrid.class);
      this.setExposed(Trigger.class);
      this.setExposed(VehicleZone.class);
      this.setExposed(Zone.class);
      this.setExposed(IsoMovingObject.class);
      this.setExposed(IsoObject.class);
      this.setExposed(IsoObjectPicker.class);
      this.setExposed(IsoPushableObject.class);
      this.setExposed(IsoUtils.class);
      this.setExposed(IsoWorld.class);
      this.setExposed(LosUtil.class);
      this.setExposed(MetaObject.class);
      this.setExposed(RoomDef.class);
      this.setExposed(SliceY.class);
      this.setExposed(TileOverlays.class);
      this.setExposed(Vector2.class);
      this.setExposed(Vector3.class);
      this.setExposed(WorldMarkers.class);
      this.setExposed(DirectionArrow.class);
      this.setExposed(GridSquareMarker.class);
      this.setExposed(PlayerHomingPoint.class);
      this.setExposed(SearchMode.class);
      this.setExposed(PlayerSearchMode.class);
      this.setExposed(SearchModeFloat.class);
      this.setExposed(IsoMarkers.class);
      this.setExposed(IsoMarker.class);
      this.setExposed(CircleIsoMarker.class);
      this.setExposed(LuaEventManager.class);
      this.setExposed(MapObjects.class);
      this.setExposed(ActiveMods.class);
      this.setExposed(Server.class);
      this.setExposed(ServerOptions.class);
      this.setExposed(BooleanServerOption.class);
      this.setExposed(DoubleServerOption.class);
      this.setExposed(IntegerServerOption.class);
      this.setExposed(StringServerOption.class);
      this.setExposed(TextServerOption.class);
      this.setExposed(ServerSettings.class);
      this.setExposed(ServerSettingsManager.class);
      this.setExposed(ZombiePopulationRenderer.class);
      this.setExposed(zombie.popman.ZombiePopulationRenderer.BooleanDebugOption.class);
      this.setExposed(RadioAPI.class);
      this.setExposed(DeviceData.class);
      this.setExposed(DevicePresets.class);
      this.setExposed(PresetEntry.class);
      this.setExposed(ZomboidRadio.class);
      this.setExposed(RadioData.class);
      this.setExposed(RadioScriptManager.class);
      this.setExposed(DynamicRadioChannel.class);
      this.setExposed(RadioChannel.class);
      this.setExposed(RadioBroadCast.class);
      this.setExposed(RadioLine.class);
      this.setExposed(RadioScript.class);
      this.setExposed(ExitOption.class);
      this.setExposed(ChannelCategory.class);
      this.setExposed(SLSoundManager.class);
      this.setExposed(StorySound.class);
      this.setExposed(StorySoundEvent.class);
      this.setExposed(EventSound.class);
      this.setExposed(DataPoint.class);
      this.setExposed(RecordedMedia.class);
      this.setExposed(MediaData.class);
      this.setExposed(MediaLineData.class);
      this.setExposed(EvolvedRecipe.class);
      this.setExposed(Fixing.class);
      this.setExposed(Fixer.class);
      this.setExposed(FixerSkill.class);
      this.setExposed(GameSoundScript.class);
      this.setExposed(Item.class);
      this.setExposed(Type.class);
      this.setExposed(ItemRecipe.class);
      this.setExposed(MannequinScript.class);
      this.setExposed(ModelAttachment.class);
      this.setExposed(ModelScript.class);
      this.setExposed(MovableRecipe.class);
      this.setExposed(Recipe.class);
      this.setExposed(RequiredSkill.class);
      this.setExposed(Result.class);
      this.setExposed(Source.class);
      this.setExposed(ScriptModule.class);
      this.setExposed(VehicleScript.class);
      this.setExposed(Area.class);
      this.setExposed(Model.class);
      this.setExposed(Part.class);
      this.setExposed(Passenger.class);
      this.setExposed(PhysicsShape.class);
      this.setExposed(Position.class);
      this.setExposed(Wheel.class);
      this.setExposed(ScriptManager.class);
      this.setExposed(TemplateText.class);
      this.setExposed(ReplaceProviderCharacter.class);
      this.setExposed(ActionProgressBar.class);
      this.setExposed(Clock.class);
      this.setExposed(UIDebugConsole.class);
      this.setExposed(ModalDialog.class);
      this.setExposed(MoodlesUI.class);
      this.setExposed(NewHealthPanel.class);
      this.setExposed(ObjectTooltip.class);
      this.setExposed(Layout.class);
      this.setExposed(LayoutItem.class);
      this.setExposed(RadarPanel.class);
      this.setExposed(RadialMenu.class);
      this.setExposed(RadialProgressBar.class);
      this.setExposed(SpeedControls.class);
      this.setExposed(TextManager.class);
      this.setExposed(UI3DModel.class);
      this.setExposed(UIElement.class);
      this.setExposed(UIFont.class);
      this.setExposed(UITransition.class);
      this.setExposed(UIManager.class);
      this.setExposed(UIServerToolbox.class);
      this.setExposed(UITextBox2.class);
      this.setExposed(VehicleGauge.class);
      this.setExposed(TextDrawObject.class);
      this.setExposed(PZArrayList.class);
      this.setExposed(PZCalendar.class);
      this.setExposed(BaseVehicle.class);
      this.setExposed(EditVehicleState.class);
      this.setExposed(BehaviorResult.class);
      this.setExposed(PathFindBehavior2.class);
      this.setExposed(PathFindState2.class);
      this.setExposed(UI3DScene.class);
      this.setExposed(VehicleDoor.class);
      this.setExposed(VehicleLight.class);
      this.setExposed(VehiclePart.class);
      this.setExposed(VehicleType.class);
      this.setExposed(VehicleWindow.class);
      this.setExposed(AttachedItem.class);
      this.setExposed(AttachedItems.class);
      this.setExposed(AttachedLocation.class);
      this.setExposed(AttachedLocationGroup.class);
      this.setExposed(AttachedLocations.class);
      this.setExposed(WornItems.class);
      this.setExposed(WornItem.class);
      this.setExposed(BodyLocation.class);
      this.setExposed(BodyLocationGroup.class);
      this.setExposed(BodyLocations.class);
      this.setExposed(DummySoundManager.class);
      this.setExposed(GameSounds.class);
      this.setExposed(GameTime.class);
      this.setExposed(GameWindow.class);
      this.setExposed(SandboxOptions.class);
      this.setExposed(BooleanSandboxOption.class);
      this.setExposed(DoubleSandboxOption.class);
      this.setExposed(StringSandboxOption.class);
      this.setExposed(EnumSandboxOption.class);
      this.setExposed(IntegerSandboxOption.class);
      this.setExposed(SoundManager.class);
      this.setExposed(SystemDisabler.class);
      this.setExposed(VirtualZombieManager.class);
      this.setExposed(WorldSoundManager.class);
      this.setExposed(WorldSound.class);
      this.setExposed(DummyCharacterSoundEmitter.class);
      this.setExposed(CharacterSoundEmitter.class);
      this.setExposed(AmbientSoundEffect.class);
      this.setExposed(BaseAmbientStreamManager.class);
      this.setExposed(AmbientStreamManager.class);
      this.setExposed(Nutrition.class);
      this.setExposed(BSFurnace.class);
      this.setExposed(MultiStageBuilding.class);
      this.setExposed(Stage.class);
      this.setExposed(SleepingEvent.class);
      this.setExposed(IsoCompost.class);
      this.setExposed(Userlog.class);
      this.setExposed(UserlogType.class);
      this.setExposed(ConfigOption.class);
      this.setExposed(BooleanConfigOption.class);
      this.setExposed(DoubleConfigOption.class);
      this.setExposed(EnumConfigOption.class);
      this.setExposed(IntegerConfigOption.class);
      this.setExposed(StringConfigOption.class);
      this.setExposed(Faction.class);
      this.setExposed(LuaFileWriter.class);
      this.setExposed(Keyboard.class);
      this.setExposed(DBResult.class);
      this.setExposed(NonPvpZone.class);
      this.setExposed(DBTicket.class);
      this.setExposed(StashSystem.class);
      this.setExposed(StashBuilding.class);
      this.setExposed(Stash.class);
      this.setExposed(ItemType.class);
      this.setExposed(RandomizedWorldBase.class);
      this.setExposed(RandomizedBuildingBase.class);
      this.setExposed(RBBurntFireman.class);
      this.setExposed(RBBasic.class);
      this.setExposed(RBBurnt.class);
      this.setExposed(RBOther.class);
      this.setExposed(RBStripclub.class);
      this.setExposed(RBSchool.class);
      this.setExposed(RBSpiffo.class);
      this.setExposed(RBPizzaWhirled.class);
      this.setExposed(RBOffice.class);
      this.setExposed(RBHairSalon.class);
      this.setExposed(RBClinic.class);
      this.setExposed(RBPileOCrepe.class);
      this.setExposed(RBCafe.class);
      this.setExposed(RBBar.class);
      this.setExposed(RBLooted.class);
      this.setExposed(RBSafehouse.class);
      this.setExposed(RBBurntCorpse.class);
      this.setExposed(RBShopLooted.class);
      this.setExposed(RBKateAndBaldspot.class);
      this.setExposed(RandomizedDeadSurvivorBase.class);
      this.setExposed(RDSZombiesEating.class);
      this.setExposed(RDSBleach.class);
      this.setExposed(RDSDeadDrunk.class);
      this.setExposed(RDSGunmanInBathroom.class);
      this.setExposed(RDSGunslinger.class);
      this.setExposed(RDSZombieLockedBathroom.class);
      this.setExposed(RDSBandPractice.class);
      this.setExposed(RDSBathroomZed.class);
      this.setExposed(RDSBedroomZed.class);
      this.setExposed(RDSFootballNight.class);
      this.setExposed(RDSHenDo.class);
      this.setExposed(RDSStagDo.class);
      this.setExposed(RDSStudentNight.class);
      this.setExposed(RDSPokerNight.class);
      this.setExposed(RDSSuicidePact.class);
      this.setExposed(RDSPrisonEscape.class);
      this.setExposed(RDSPrisonEscapeWithPolice.class);
      this.setExposed(RDSSkeletonPsycho.class);
      this.setExposed(RDSCorpsePsycho.class);
      this.setExposed(RDSSpecificProfession.class);
      this.setExposed(RDSPoliceAtHouse.class);
      this.setExposed(RDSHouseParty.class);
      this.setExposed(RDSTinFoilHat.class);
      this.setExposed(RDSHockeyPsycho.class);
      this.setExposed(RandomizedVehicleStoryBase.class);
      this.setExposed(RVSCarCrash.class);
      this.setExposed(RVSBanditRoad.class);
      this.setExposed(RVSAmbulanceCrash.class);
      this.setExposed(RVSCrashHorde.class);
      this.setExposed(RVSCarCrashCorpse.class);
      this.setExposed(RVSPoliceBlockade.class);
      this.setExposed(RVSPoliceBlockadeShooting.class);
      this.setExposed(RVSBurntCar.class);
      this.setExposed(RVSConstructionSite.class);
      this.setExposed(RVSUtilityVehicle.class);
      this.setExposed(RVSChangingTire.class);
      this.setExposed(RVSFlippedCrash.class);
      this.setExposed(RVSTrailerCrash.class);
      this.setExposed(RandomizedZoneStoryBase.class);
      this.setExposed(RZSForestCamp.class);
      this.setExposed(RZSForestCampEaten.class);
      this.setExposed(RZSBuryingCamp.class);
      this.setExposed(RZSBeachParty.class);
      this.setExposed(RZSFishingTrip.class);
      this.setExposed(RZSBBQParty.class);
      this.setExposed(RZSHunterCamp.class);
      this.setExposed(RZSSexyTime.class);
      this.setExposed(RZSTrapperCamp.class);
      this.setExposed(RZSBaseball.class);
      this.setExposed(RZSMusicFestStage.class);
      this.setExposed(RZSMusicFest.class);
      this.setExposed(MapGroups.class);
      this.setExposed(BeardStyles.class);
      this.setExposed(BeardStyle.class);
      this.setExposed(HairStyles.class);
      this.setExposed(HairStyle.class);
      this.setExposed(BloodClothingType.class);
      this.setExposed(WeaponType.class);
      this.setExposed(IsoWaterGeometry.class);
      this.setExposed(ModData.class);
      this.setExposed(WorldMarkers.class);
      this.setExposed(ChatMessage.class);
      this.setExposed(ChatBase.class);
      this.setExposed(ServerChatMessage.class);
      this.setExposed(Safety.class);
      if (Core.bDebug) {
         this.setExposed(Field.class);
         this.setExposed(Method.class);
         this.setExposed(Coroutine.class);
      }

      UIWorldMap.setExposed(this);
      if (Core.bDebug) {
         try {
            this.exposeMethod(Class.class, Class.class.getMethod("getName"), LuaManager.env);
            this.exposeMethod(Class.class, Class.class.getMethod("getSimpleName"), LuaManager.env);
         } catch (NoSuchMethodException var3) {
            var3.printStackTrace();
         }
      }

      for (Class var2 : this.exposed) {
         this.exposeLikeJavaRecursively(var2, LuaManager.env);
      }

      this.exposeGlobalFunctions(new GlobalObject());
      LuaManager.exposeKeyboardKeys(LuaManager.env);
      LuaManager.exposeLuaCalendar();
   }

   public void setExposed(Class<?> var1) {
      this.exposed.add(var1);
   }

   public boolean shouldExpose(Class<?> var1) {
      return var1 == null ? false : this.exposed.contains(var1);
   }
}
