#!/bin/bash
# Quick reference for Vineflower + Rosetta integration
# Place this script in /workspaces/PZ/ for easy reference

echo "Project Zomboid Decompilation + Documentation Integration"
echo "=========================================================="
echo ""
echo "QUICK START:"
echo "-----------"
echo ""
echo "1. Basic Decompilation with Rosetta Enhancement:"
echo "   python3 decompile_vineflower.py /workspaces/PZ/classes_only /workspaces/PZ/converted"
echo ""
echo "2. Fast Decompilation (skip documentation):"
echo "   python3 decompile_vineflower.py /workspaces/PZ/classes_only /workspaces/PZ/converted --skip-rosetta"
echo ""
echo "3. Extract Rosetta Metadata to JSON:"
echo "   python3 tools/rosetta_extractor.py /workspaces/PZ/class_map.json"
echo ""
echo "STRUCTURE:"
echo "---------"
echo ""
echo "Input:  /workspaces/PZ/classes_only/          (3,250 .class files)"
echo "Source: /workspaces/PZ/pz-rosetta-source-main (Documentation YAML files)"
echo "Output: /workspaces/PZ/converted/             (Decompiled + enhanced Java files)"
echo ""
echo "WHAT'S ENHANCED:"
echo "---------------"
echo "✓ Class documentation (JavaDoc style)"
echo "✓ Method documentation and parameters"
echo "✓ Field documentation"
echo "✓ Type information"
echo "✓ Inheritance relationships"
echo ""
echo "FILES INVOLVED:"
echo "---------------"
echo "decompile_vineflower.py        - Main decompilation script with Rosetta integration"
echo "tools/rosetta_extractor.py     - Extract Rosetta metadata"
echo "pz-rosetta-source-main/        - Source of documentation (2800+ classes)"
echo "ZomboidDecompiler/lib/         - Vineflower decompiler library"
echo ""
echo "NEXT STEPS:"
echo "-----------"
echo "After decompilation:"
echo ""
echo "1. Run Java converter to convert to C++:"
echo "   python3 java_converter.py /workspaces/PZ/converted /workspaces/PZ/converted_cpp"
echo ""
echo "2. Generate documentation:"
echo "   Generate JavaDocs from enhanced source"
echo ""
echo "3. Analyze code structure:"
echo "   Use extracted metadata for architecture analysis"
echo ""
