#include "fmod/SWIGTYPE_p_FMOD_ADVANCEDSETTINGS.h"

namespace fmod {

protected
SWIGTYPE_p_FMOD_ADVANCEDSETTINGS::SWIGTYPE_p_FMOD_ADVANCEDSETTINGS(long long0,
 bool var3) {
 // TODO: Implement SWIGTYPE_p_FMOD_ADVANCEDSETTINGS
 return nullptr;
}

protected
SWIGTYPE_p_FMOD_ADVANCEDSETTINGS::SWIGTYPE_p_FMOD_ADVANCEDSETTINGS() {
 // TODO: Implement SWIGTYPE_p_FMOD_ADVANCEDSETTINGS
 return nullptr;
}

long SWIGTYPE_p_FMOD_ADVANCEDSETTINGS::getCPtr(
 SWIGTYPE_p_FMOD_ADVANCEDSETTINGS sWIGTYPE_p_FMOD_ADVANCEDSETTINGS) {
 // TODO: Implement getCPtr
 return 0;
}

} // namespace fmod
