#include "fmod/SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE.h"

namespace fmod {

protected
SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE::SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE(
 long long0, bool var3) {
 // TODO: Implement SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE
 return nullptr;
}

protected
SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE::SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE() {
 // TODO: Implement SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE
 return nullptr;
}

long SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE::getCPtr(
 SWIGTYPE_p_FMOD_DSPCONNECTION_TYPE sWIGTYPE_p_FMOD_DSPCONNECTION_TYPE) {
 // TODO: Implement getCPtr
 return 0;
}

} // namespace fmod
