#include "fmod/SWIGTYPE_p_FMOD_REVERB_PROPERTIES.h"

namespace fmod {

protected
SWIGTYPE_p_FMOD_REVERB_PROPERTIES::SWIGTYPE_p_FMOD_REVERB_PROPERTIES(
 long long0, bool var3) {
 // TODO: Implement SWIGTYPE_p_FMOD_REVERB_PROPERTIES
 return nullptr;
}

protected
SWIGTYPE_p_FMOD_REVERB_PROPERTIES::SWIGTYPE_p_FMOD_REVERB_PROPERTIES() {
 // TODO: Implement SWIGTYPE_p_FMOD_REVERB_PROPERTIES
 return nullptr;
}

long SWIGTYPE_p_FMOD_REVERB_PROPERTIES::getCPtr(
 SWIGTYPE_p_FMOD_REVERB_PROPERTIES sWIGTYPE_p_FMOD_REVERB_PROPERTIES) {
 // TODO: Implement getCPtr
 return 0;
}

} // namespace fmod
